name: keystore_manager
description: Manage and protect the 'keystore' private key file, support the 'keystore' structure and address structure defined by ECDSA / bip32 / bip39 / bip44.
version: 1.0.0
homepage: https://github.com/LmFlutterSDK/keystore_manager

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  web3dart: ^2.3.5
  path_provider: ^2.0.9
  bip39: ^1.0.6
  bip32: ^2.0.0
  http: ^0.13.4
  typed_data: ^1.3.0

dev_dependencies:
  test:
